Update nix pin with `make nixpkgs`
containers/conmon pull request #243
Opened 2021-03-07 13:51 UTC by hswong3i

2021-03-08 09:13 UTC, saschagrunert requested changes
Both builds timed out. Can you try to increase the timeout that we can pre-populate the cache? If the builds succeed, then we can in theory reduce the timeout again because we have a cache.

2021-03-13 03:50 UTC, hswong3i commented
@saschagrunert `gitMinimal` failed with `perlPackages.libwww-perl` during static build, therefore recent PR remove it.

2021-03-15 08:14 UTC, saschagrunert commented
> @saschagrunert `gitMinimal` failed with `perlPackages.libwww-perl` during static build, therefore recent PR remove it.

Yeah sounds reasonable, but the builds still timeout. Can you try the timeout removal please?

2021-03-15 14:24 UTC, hswong3i commented
> > @saschagrunert `gitMinimal` failed with `perlPackages.libwww-perl` during static build, therefore recent PR remove it.
> 
> Yeah sounds reasonable, but the builds still timeout. Can you try the timeout removal please?

Oops where is the timeout? https://github.com/containers/conmon/blob/master/.cirrus.yml#L148 ??

2021-03-15 14:38 UTC, saschagrunert commented
> > > @saschagrunert `gitMinimal` failed with `perlPackages.libwww-perl` during static build, therefore recent PR remove it.
> > 
> > 
> > Yeah sounds reasonable, but the builds still timeout. Can you try the timeout removal please?
> 
> Oops where is the timeout? https://github.com/containers/conmon/blob/master/.cirrus.yml#L148 ??

Yes, that's the line :)

2021-03-16 08:33 UTC, saschagrunert commented on .cirrus.yml
> -    timeout_in: '20m'
I think we have to set it to `0` to remove the default timeout of 120m

2021-05-06 03:53 UTC, hswong3i commented
@saschagrunert may this PR have your kindly review and approval?

2021-06-03 07:54 UTC, hswong3i commented
@saschagrunert https://github.com/NixOS/nixpkgs/releases/tag/21.05 released so we could debug the build for `aarch64-unknown-linux-gnu` again ;-)

2021-06-18 14:56 UTC, rhatdan commented
I would figure the static tests have to pass to merge this.

2021-06-18 15:35 UTC, cevich commented
> but the builds still timeout.

FYI (not sure if it's relevant or not): Cirrus-CI has a hard-timeout of 2-hours, there is no configuration to get past this if it's being hit.

2021-07-26 14:44 UTC, hswong3i commented
I am moving my Ansible Role to using kubic repo.

2021-07-26 14:44 UTC, closed without merging